<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="2359s-MacBook-Pro.local" name="com.media2359.tests.b_CalendarView" tests="7" failures="1" timestamp="10 Jul 2020 00:24:36 GMT" time="484.719" errors="0">
  <testcase name="B_006_viewLogDetail" time="20.519" classname="com.media2359.tests.b_CalendarView">
    <failure type="java.lang.AssertionError" message="Index: 0, Size: 0">
      <![CDATA[java.lang.AssertionError: Index: 0, Size: 0
at org.testng.Assert.fail(Assert.java:96)
at com.media2359.tests.b_CalendarView.B_006_viewLogDetail(b_CalendarView.java:323)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.media2359.App.main(App.java:40)
]]>
    </failure>
  </testcase> <!-- B_006_viewLogDetail -->
  <testcase name="B_001_viewDutyHoursCalendar" time="43.520" classname="com.media2359.tests.b_CalendarView"/>
  <testcase name="B_004_cancelLoggingHoursUponLogging" time="47.347" classname="com.media2359.tests.b_CalendarView"/>
  <testcase name="B_007_viewViolationsFromCalendarViewScreen" time="56.073" classname="com.media2359.tests.b_CalendarView"/>
  <testcase name="B_002_addNewLogBybutton" time="208.142" classname="com.media2359.tests.b_CalendarView"/>
  <testcase name="B_005_deleteLogHoursBlockUponLogging" time="65.369" classname="com.media2359.tests.b_CalendarView"/>
  <testcase name="B_003_addNewLogByDragging" time="43.749" classname="com.media2359.tests.b_CalendarView"/>
</testsuite> <!-- com.media2359.tests.b_CalendarView -->
