<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="2359s-MacBook-Pro.local" failures="1" tests="1" name="com.media2359.tests.a_Authentication" time="38.893" errors="0" timestamp="11 Aug 2020 09:56:24 GMT" skipped="0">
  <testcase classname="com.media2359.tests.a_Authentication" name="A_001_LaunchApp" time="38.893">
    <failure message="Expected condition failed: waiting for visibility of Located by By.chained({By.xpath: //XCUIElementTypeButton[@name=&#039;Forgot password?&#039;]}) (tried for 10 second(s) with 500 milliseconds interval)" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected condition failed: waiting for visibility of Located by By.chained({By.xpath: //XCUIElementTypeButton[@name='Forgot password?']}) (tried for 10 second(s) with 500 milliseconds interval)
at org.testng.Assert.fail(Assert.java:96)
at com.media2359.tests.a_Authentication.A_001_LaunchApp(a_Authentication.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.media2359.App.main(App.java:40)
]]>
    </failure>
  </testcase> <!-- A_001_LaunchApp -->
</testsuite> <!-- com.media2359.tests.a_Authentication -->
