<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="2359s-MacBook-Pro.local" name="com.media2359.tests.d_LogDetail" tests="8" failures="3" timestamp="10 Jul 2020 00:24:36 GMT" time="302.750" errors="0">
  <testcase name="D_002_deleteLog" time="33.371" classname="com.media2359.tests.d_LogDetail"/>
  <testcase name="D_007_selectViolationsCause" time="0.000" classname="com.media2359.tests.d_LogDetail">
    <skipped/>
  </testcase> <!-- D_007_selectViolationsCause -->
  <testcase name="D_008_changeViolationsCause" time="0.000" classname="com.media2359.tests.d_LogDetail">
    <skipped/>
  </testcase> <!-- D_008_changeViolationsCause -->
  <testcase name="D_004_sendComment" time="8.394" classname="com.media2359.tests.d_LogDetail">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.media2359.pages.BasePage.assertTrue(BasePage.java:297)
at com.media2359.pages.LogDetailPage.verifyInputCommentsLD(LogDetailPage.java:140)
at com.media2359.tests.d_LogDetail.D_004_sendComment(d_LogDetail.java:237)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.media2359.App.main(App.java:40)
]]>
    </failure>
  </testcase> <!-- D_004_sendComment -->
  <testcase name="D_001_editLog" time="190.769" classname="com.media2359.tests.d_LogDetail"/>
  <testcase name="D_003_viewComments" time="48.704" classname="com.media2359.tests.d_LogDetail"/>
  <testcase name="D_005_viewViolations" time="10.277" classname="com.media2359.tests.d_LogDetail">
    <failure type="java.lang.AssertionError" message="Can&#039;t locate an element by this strategy: By.chained({By.xpath: //XCUIElementTypeNavigationBar//XCUIElementTypeStaticText[1]})">
      <![CDATA[java.lang.AssertionError: Can't locate an element by this strategy: By.chained({By.xpath: //XCUIElementTypeNavigationBar//XCUIElementTypeStaticText[1]})
at org.testng.Assert.fail(Assert.java:96)
at com.media2359.tests.d_LogDetail.D_005_viewViolations(d_LogDetail.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.media2359.App.main(App.java:40)
]]>
    </failure>
  </testcase> <!-- D_005_viewViolations -->
  <testcase name="D_006_viewViolationsFromListViewScreen" time="11.235" classname="com.media2359.tests.d_LogDetail">
    <failure type="java.lang.AssertionError" message="Can&#039;t locate an element by this strategy: By.chained({By.xpath: //XCUIElementTypeNavigationBar//XCUIElementTypeStaticText[1]})">
      <![CDATA[java.lang.AssertionError: Can't locate an element by this strategy: By.chained({By.xpath: //XCUIElementTypeNavigationBar//XCUIElementTypeStaticText[1]})
at org.testng.Assert.fail(Assert.java:96)
at com.media2359.tests.d_LogDetail.D_006_viewViolationsFromListViewScreen(d_LogDetail.java:306)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.media2359.App.main(App.java:40)
]]>
    </failure>
  </testcase> <!-- D_006_viewViolationsFromListViewScreen -->
</testsuite> <!-- com.media2359.tests.d_LogDetail -->
